image: swift:latest

before_script:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"

stages: 
  - build
  - test

build_project:
  stage: build
  script:
    - swift package reset
    - swift build
  tags:
    - swift

test_project:
  stage: test
  script:
    - swift package reset
    - swift test
  tags:
    - swift