author: "Christian Treffs"
clean: true
documentation: "docs/*.md"
github_url: "https://github.com/fireblade-engine/ecs"
hide_documentation_coverage: false
min_acl: "public"
module: "FirebladeECS"
module_version: 0.9.0
output: "docs"
readme: "README.md"
skip_undocumented: false
theme: fullwidth
