name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-macOS-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: swift build -c release
    - name: Test Release
      run: swift test -c release --skip-build --skip-update --parallel

  build-test-ubuntu-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: swift build -c release
    - name: Test Release
      run: swift test -c release --skip-build --skip-update --parallel
