name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-macOS-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: swift test --skip-update --parallel
    - name: Build Release
      run: swift build -c release

  build-test-ubuntu-latest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: swift test --skip-update --parallel
    - name: Build Release
      run: swift build -c release
