name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/documentation.yml
      - Sources/FirebladeECS/**.swift

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@1.0.0-beta.3
        with:
          inputs: "Sources/FirebladeECS"
          output: "Documentation"
      - name: Publish to GitHub Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@1.0.0
        with:
          path: "Documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
